<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 
   <!-- document element -->
   <xs:simpleType name="FloatList">
	   <xs:list itemType="xs:float"/>
   </xs:simpleType>
   <xs:element name="parameters">
     <xs:complexType>
       <xs:all>
         <xs:element ref="input_cyrano"/>
         <xs:element name="verbosity" type="xs:integer" minOccurs="0">
           <xs:annotation><xs:documentation>Determines how much information the code will print to stdout and stderr</xs:documentation></xs:annotation>
         </xs:element>
         <xs:element name="rm_tmp" type="xs:boolean" minOccurs="0">
            <xs:annotation>
                <xs:documentation>true: Delete temporary data folder</xs:documentation>
            </xs:annotation>
         </xs:element>
       </xs:all>
     </xs:complexType>
   </xs:element>
 
   <xs:element name="input_cyrano">
     <xs:complexType>
       <xs:all>

	 <xs:element name="Npol" type="xs:integer">
	   <xs:annotation>
             <xs:documentation>Number of poloidal points</xs:documentation>
	   </xs:annotation>
	 </xs:element>
	 <xs:element name="Np_out" type="xs:integer">
	   <xs:annotation><xs:documentation>Number of OUTPUT radial points (0:equilibrium, &gt;1:value)</xs:documentation></xs:annotation>
	 </xs:element>
	 <xs:element name="BC_axis" type="xs:integer">
	   <xs:annotation><xs:documentation>Axis boundary conditions test (0:circular BC, 1:D-shape BC)</xs:documentation></xs:annotation>
	 </xs:element>
	 <xs:element name="fix_triang" type="xs:boolean">
	   <xs:annotation><xs:documentation>true: Fixed triangularity (edge value); false: Use triangularity fprofile from equilibrium CPO</xs:documentation></xs:annotation>
	 </xs:element>
	 <xs:element name="smooth" type="xs:boolean">
	   <xs:annotation><xs:documentation>true: Smooth power deposition profiles in case of tangent resonances (e.g. for large Npol); false: Don't smooth</xs:documentation></xs:annotation>
	 </xs:element>
 
	 <xs:element name="self_consistent">
	   <xs:complexType>
	     <xs:all>
	       <xs:element name="iterate_Teff" type="xs:boolean">
		 <xs:annotation><xs:documentation>Internal self-consistent calc. with Teff from Stix_Simple</xs:documentation></xs:annotation>
	       </xs:element>
	       <xs:element name="target_ions" type="xs:integer">
		 <xs:annotation><xs:documentation>ion index for single species Teff calc. (0 = iterate on all ions)</xs:documentation></xs:annotation>
	       </xs:element>
	       <xs:element name="Npstix" type="xs:integer">
		 <xs:annotation><xs:documentation>No. of points for v-grid for the internal Stix solver</xs:documentation></xs:annotation>
	       </xs:element>
	       <xs:element name="gaussian_teff" type="xs:boolean">
		 <xs:annotation><xs:documentation>true: Use Gaussian treatment of Teff; false: Use Teff directly from Stix subroutine</xs:documentation></xs:annotation>
	       </xs:element>
	     </xs:all>
	   </xs:complexType>
	 </xs:element>
	 <xs:element name="fast_particles">
	   <xs:complexType>
	     <xs:all>
	       <xs:element name="include_nbi" type="xs:integer">
		 <xs:annotation><xs:documentation>Include NBI species (0: don't include, 1: from corefast, 2: from distribution, 3: from distribution with 3 energy sources)-</xs:documentation></xs:annotation>
	       </xs:element>
	       <xs:element name="include_fasticrh" type="xs:integer">
		 <xs:annotation><xs:documentation>Include ICRH heated species (0: don't include, 1: from corefast, 2: from distribution) -NOT READY-</xs:documentation></xs:annotation>
	       </xs:element>
	       <xs:element name="include_alphas" type="xs:integer">
		 <xs:annotation><xs:documentation>Include fast alphas from corefast (0: don't include, 1: from corefast, 2: from distribution) -NOT READY-</xs:documentation></xs:annotation>
	       </xs:element>
	     </xs:all>
	   </xs:complexType>
	 </xs:element>

	 <xs:element name="overwrite_params">
	   <xs:complexType>
	     <xs:all>

	       <xs:element name="RF">
		 <xs:complexType>
		   <xs:all>
		     <xs:element name="total_power" type="FloatList">
		       <xs:annotation><xs:documentation>Total RF Power [W] (0:waves, 1: antennas, &gt;1:value)</xs:documentation></xs:annotation>
		     </xs:element>
		     <xs:element name="frequency" type="FloatList">
		       <xs:annotation><xs:documentation>RF frequency (Hz)</xs:documentation></xs:annotation>
		     </xs:element>
                     <xs:element name="orbit_width" type="FloatList">
                       <xs:annotation><xs:documentation>Orbit width (m) (0:no averaging, &gt;0:averaging size) </xs:documentation></xs:annotation>
                     </xs:element>

		     <xs:element name="Ntor" type="xs:integer">
		       <xs:annotation><xs:documentation>Single toroidal mode number (0:waves, &gt;0:value)</xs:documentation></xs:annotation>
		     </xs:element>
		   </xs:all>
		 </xs:complexType>
	       </xs:element>
	       <xs:element name="impose_antenna" type="xs:boolean"/>
	       <xs:element name="antenna_geometry">
		 <xs:complexType>
		   <xs:all>
		     
		     <xs:element name="R_antenna" type="xs:float"/>
		     <xs:element name="theta_antenna_min" type="xs:float"/>
		     <xs:element name="theta_antenna_max" type="xs:float"/>

		   </xs:all>
		 </xs:complexType>
	       </xs:element>
	       
	       <xs:element name="nullify_Ip" type="xs:boolean"/>

	     </xs:all>
	   </xs:complexType>
	 </xs:element>
       </xs:all>
     </xs:complexType>
   </xs:element>
 </xs:schema>
