#!/usr/bin/env bash
# ----------------------------------------------------------------------------
# HCD Workflow Environment Setup (MUSCLE3 + Intel Toolchain + DD 4.0.0)
#
# Updated for compatibility with Fortran torbeam_m3.exe (DD 4.0.0)
#
# This script bootstraps the execution environment by:
#   1. Loading the required Intel toolchain and modules (DD 4.0.0).
#   2. Creating a clean virtual environment.
#   3. Linking system Intel-Numpy to avoid ABI conflicts.
#   4. Preparing necessary input data files.
#   5. Generating execution wrappers (run_env.sh, run_benchmark.sh).
#
# Usage:
#   chmod +x config_hcd_m3.sh
#   ./config_hcd_m3.sh
# ----------------------------------------------------------------------------

# --- Configuration ---
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${REPO_ROOT}/devenv_m3"

# Define modules for DD 4.0.0 (matching Torbeam standalone config_sdcc.sh)
CORE_MODULES=(
    "IMAS-Python/2.0.1-intel-2023b"
    "IMAS-AL-Fortran"
    "MUSCLE3"
    "XMLlib"
    "INTERPOS"
    "IDStools"
)

# Waveform-Cooker path (local version like Torbeam uses)
WAVEFORM_COOKER_PATH="/home/ITER/schneim/public/git/waveform-cooker"

echo "=========================================================="
echo "   HCD Workflow MUSCLE3 Environment Setup (DD 4.0.0)"
echo "=========================================================="

# --- Step 1: Load Environment Modules ---
echo "[1/6] Loading DD 4.0.0 Environment..."
module purge >/dev/null 2>&1 || true

for mod in "${CORE_MODULES[@]}"; do
    echo "  -> Loading $mod"
    module load "$mod"
done

# Verify IMAS version
echo ""
echo "  Loaded IMAS version: $IMAS_VERSION"
echo "  DD version: $(module list 2>&1 | grep -o 'Data-Dictionary/[^ ]*' || echo 'check manually')"

# Verify compiler availability
if ! command -v ifort &> /dev/null; then
    echo "Error: Intel compiler (ifort) not found. Check module loading."
    exit 1
fi

# Detect System Numpy Path
echo ""
echo "  -> Detecting System Numpy location..."
SYSTEM_NUMPY_FILE=$(python -c "import numpy; print(numpy.__file__)")
SYSTEM_NUMPY_DIR=$(dirname "${SYSTEM_NUMPY_FILE}")
SYSTEM_SCIPY_DIR="${SYSTEM_NUMPY_DIR}/../scipy"

if [[ ! -d "${SYSTEM_NUMPY_DIR}" ]]; then
    echo "Error: Could not detect System Numpy. Check modules."
    exit 1
fi
echo "     Found: ${SYSTEM_NUMPY_DIR}"

# --- Step 2: Setup Virtual Environment ---
echo ""
echo "[2/6] Setting up Virtual Environment (${VENV_DIR})..."
export PYTHONNOUSERSITE=1

if [[ -d "${VENV_DIR}" ]]; then
    echo "  -> Removing existing venv..."
    rm -rf "${VENV_DIR}"
fi

python3 -m venv --system-site-packages "${VENV_DIR}"
source "${VENV_DIR}/bin/activate"

# --- Step 3: Install Dependencies & Fix Numpy ---
echo ""
echo "[3/6] Installing Dependencies..."
pip install --upgrade pip --quiet
pip install regex lxml yatiml msgpack-python --quiet

# Uninstall conflicting packages
pip uninstall -y numpy scipy >/dev/null 2>&1 || true

# Enter site-packages
SITE_PACKAGES="${VENV_DIR}/lib/python3.11/site-packages"
cd "${SITE_PACKAGES}"

# Clean residual numpy/scipy folders
rm -rf numpy numpy-* scipy scipy-*

# Create Symlinks to System Intel Numpy/Scipy
ln -s "${SYSTEM_NUMPY_DIR}" ./numpy
ln -s "${SYSTEM_SCIPY_DIR}" ./scipy
echo "  -> Symlinks created pointing to System Libraries."

cd "${REPO_ROOT}"

# --- Step 4: Prepare Input Data ---
echo ""
echo "[4/6] Preparing Input Data..."

# Create benchmark test folder
BENCHMARK_DIR="${REPO_ROOT}/tests/m3_benchmark"
if [[ ! -d "${BENCHMARK_DIR}" ]]; then
    mkdir -p "${BENCHMARK_DIR}"
    echo "  -> Created ${BENCHMARK_DIR}"
fi

# --- Step 5: Generate Execution Scripts ---
echo ""
echo "[5/6] Generating 'run_env.sh' and 'run_benchmark.sh'..."

# Generate run_env.sh for DD 4.0.0
cat > run_env.sh <<'RUNENV_EOF'
#!/bin/bash
# Auto-generated by config_hcd_m3.sh (DD 4.0.0 version)

# 1. Shield against user site packages
export PYTHONNOUSERSITE=1

# 2. Load DD 4.0.0 Environment (matching Torbeam standalone)
source /etc/profile.d/modules.sh
module purge

# Load modules (same as Torbeam config_sdcc.sh)
module load IMAS-Python/2.0.1-intel-2023b
module load IMAS-AL-Fortran
module load MUSCLE3
module load XMLlib
module load INTERPOS
module load IDStools

# Disable some access layer checks (like Torbeam)
export IMAS_AL_DISABLE_VALIDATE=1

# 3. Waveform-Cooker (local version)
export PYTHONPATH=/home/ITER/schneim/public/git/waveform-cooker:$PYTHONPATH
export EBROOTWAVEFORMMINCOOKER=/home/ITER/schneim/public/git/waveform-cooker

# 4. Determine Paths (Dynamic)
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${REPO_ROOT}/devenv_m3"

# 5. Activate Virtual Environment
source "${VENV_DIR}/bin/activate"

# 6. Configure PYTHONPATH
VENV_LIB="${VENV_DIR}/lib/python3.11/site-packages"
export PYTHONPATH="${VENV_LIB}:${REPO_ROOT}:$PYTHONPATH"

# 7. Execute Command
exec "${VENV_DIR}/bin/python" "$@"
RUNENV_EOF

chmod +x run_env.sh

# Generate run_benchmark.sh
cat > run_benchmark.sh <<'RUNBENCH_EOF'
#!/bin/bash
# Run HCD-Workflow with Fortran Torbeam M3 (DD 4.0.0)

unset MUSCLE_CONFIGURATION
unset MUSCLE_INSTANCE

BASE_DIR="run_test"
YMMSL_FILE="test_torbeam_fortran.ymmsl"

mkdir -p "$BASE_DIR"

# Find next test number
NEXT_NUM=1
while true; do
    TRY_DIR="$BASE_DIR/test$(printf "%03d" $NEXT_NUM)"
    if [ ! -d "$TRY_DIR" ]; then
        DIR_NAME="$TRY_DIR"
        break
    fi
    NEXT_NUM=$((NEXT_NUM + 1))
done

mkdir -p "$DIR_NAME"

echo "=========================================="
echo "HCD-Workflow + Fortran Torbeam M3 (DD 4.0.0)"
echo "=========================================="
echo "Output directory: $DIR_NAME"
echo "YMMSL file: $YMMSL_FILE"
echo "=========================================="

./run_env.sh \
    -m muscle3.muscle_manager \
    --start-all \
    --run-dir "$DIR_NAME" \
    "$YMMSL_FILE"
RUNBENCH_EOF

chmod +x run_benchmark.sh

# --- Step 6: Print Summary ---
echo ""
echo "=========================================================="
echo "   SETUP COMPLETE! DD 4.0.0 Environment Ready."
echo "=========================================================="
echo ""
echo "Current module list:"
module list 2>&1 | head -20
echo ""
echo "Next steps:"
echo "  1. Copy test files to tests/m3_benchmark/"
echo "  2. Copy test_torbeam_fortran.ymmsl to repo root"
echo "  3. Run: ./run_benchmark.sh"
echo "=========================================================="