#!/usr/bin/env python
import argparse

from workflow.hcd_wrapper import hcd_wrapper

# Management of input arguments
parser = argparse.ArgumentParser(description='---- Run the H&CD workflow without the interface')
parser.add_argument("-c","--config_folder",help="input configuration folder", required=True)

args = vars(parser.parse_args())
config_folder  = args["config_folder"]

hcd_wrapper(config_folder)
