#!/usr/bin/env python
import argparse,os

from src.hcd_workflow import HCDWorkflow

# Management of input arguments
parser = argparse.ArgumentParser(description='---- Run the H&CD workflow without the interface')
parser.add_argument("-c","--config_folder",help="input configuration folder", required=True)

args = vars(parser.parse_args())
config_folder  = args["config_folder"]


hcdWorkflow = HCDWorkflow(os.path.abspath(config_folder))
hcdWorkflow.initialize()
hcdWorkflow.run()
hcdWorkflow.finalize()