#!/usr/bin/env python
import argparse
import os
import sys

import imas
from waveform_cooker import add_dynamic
from wftools.wf_tools import create_workflow_param_from_file

from src.workflow_dbhelper import WorkflowDbHelper
from src.workflow_globals_reader import WorkflowGlobalsReader
from src.workflow_manager import WorkflowManager

# Management of input arguments
parser = argparse.ArgumentParser(
    description="---- Run the H&CD workflow without the interface"
)
parser.add_argument(
    "-c", "--config_folder", help="input configuration folder", required=True
)

args = vars(parser.parse_args())
config_folder = args["config_folder"]

config_folder_path = os.path.abspath(config_folder)

rootPath = os.path.dirname(os.path.abspath(__file__))
globalListPath = os.path.join(rootPath, r"global_configuration/global_lists.yaml")
inputworkflow_xml = os.path.join(config_folder_path, "input_workflow.xml")

wf_parameters = create_workflow_param_from_file(inputworkflow_xml)[
    "workflow_parameters"
][0]

input_user_or_path = wf_parameters["input_user_or_path"][0]
input_database = wf_parameters["input_database"][0]
output_user_or_path = wf_parameters["output_user_or_path"][0]
output_database = wf_parameters["output_database"][0]
shot_nr = wf_parameters["shot_nr"][0]
run_in = wf_parameters["run_in"][0]
run_out = wf_parameters["run_out"][0]

dbhelper = WorkflowDbHelper(
    input_user_or_path,
    input_database,
    output_user_or_path,
    output_database,
    shot_nr,
    run_in,
    run_out,
)
inputDb = dbhelper.getInputDatabase()
outputDb = dbhelper.getOutputDatabase()
machineDb = dbhelper.getMachineDatabase()

globallistReader = WorkflowGlobalsReader(globalListPath)
inputIds = globallistReader.getIdsScenarioList()
inputMds = globallistReader.getIdsMdList()


inputMdsDict = {}
for idsName in inputMds:
    inputMdsDict[idsName] = inputDb.get(idsName)

waveform_presets = globallistReader.getWaveformPresetsList()
for idsObject in inputMdsDict.values():
    # Overwrite with configured waveform if it exists
    for filename in os.listdir(config_folder_path):
        filePath = os.path.join(config_folder_path, filename)
        if filePath.endswith("waveforms.yaml"):
            if os.path.exists(filePath):
                idsObject = add_dynamic(filePath)
            machineDb.put(idsObject)

timeArray = dbhelper.getTimeArray(inputDb)

timenow = 320.00
idsslices = {}
for ids in inputIds:
    idsslices[ids] = inputDb.get_slice(ids, timenow, 1)

mdidsslices = {}
for ids in inputMds:
    mdidsslices[ids] = machineDb.get_slice(ids, timenow, 1)

hcdWorkflow = WorkflowManager(config_folder_path)
hcdWorkflow.initializeSlice()
hcdWorkflow.runSlice(idsslices, mdidsslices, timenow)
hcdWorkflow.finalize()

inputDb.close()
outputDb.close()
