shot number: 7897
run number: 1

## SET POWER - enter as power-time-pairs (time - time of change, power - power to change to)
## if the power from the input pulse_schedule should be used set    power = []
## if the power is constant set time to    time = [0]

nbi power:  [0., 330000000., 5454]    
nbi time:   [0., 200.      , 220. ]          

ic power: []     
ic time:  [0]

ec power: [555.]    
ec time:  [0]


## SET FREQUENCY - 
frequency ic: 40000000  
frequency ec: 40000000

## SET ENERGY
# NBI Energy is set according to beam perveance constraint depending on NBI power
