#!/bin/bash
# Auto-generated by config_hcd_m3.sh (DD 4.0.0 version)

# 1. Shield against user site packages
export PYTHONNOUSERSITE=1

# 2. Load DD 4.0.0 Environment (matching Torbeam standalone)
source /etc/profile.d/modules.sh
module purge

# Load modules (same as Torbeam config_sdcc.sh)
module load IMAS-Python/2.0.1-intel-2023b
module load IMAS-AL-Fortran
module load MUSCLE3
module load XMLlib
module load INTERPOS
module load IDStools

# Disable some access layer checks (like Torbeam)
export IMAS_AL_DISABLE_VALIDATE=1

# 3. Waveform-Cooker (local version)
export PYTHONPATH=/home/ITER/schneim/public/git/waveform-cooker:$PYTHONPATH
export EBROOTWAVEFORMMINCOOKER=/home/ITER/schneim/public/git/waveform-cooker

# 4. Determine Paths (Dynamic)
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${REPO_ROOT}/devenv_m3"

# 5. Activate Virtual Environment
source "${VENV_DIR}/bin/activate"

# 6. Configure PYTHONPATH
VENV_LIB="${VENV_DIR}/lib/python3.11/site-packages"
export PYTHONPATH="${VENV_LIB}:${REPO_ROOT}:$PYTHONPATH"

# 7. Execute Command
exec "${VENV_DIR}/bin/python" "$@"
