<?xml version="1.0" encoding="UTF-8"?>

 <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	   elementFormDefault="qualified">
   <xs:annotation>
     <xs:documentation>Code parameters for TORBEAM wrapper</xs:documentation>
   </xs:annotation>
 
   <xs:simpleType name="integer_minmaxInclusive_shot">
     <xs:restriction base="xs:integer">
       <xs:minInclusive value="1"/>
       <xs:maxInclusive value="999999"/>
     </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="integer_minmaxInclusive_run">
     <xs:restriction base="xs:integer">
       <xs:minInclusive value="1"/>
       <xs:maxInclusive value="9999"/>
     </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="integer_minmaxInclusive_02">
     <xs:restriction base="xs:integer">
       <xs:minInclusive value="0"/>
       <xs:maxInclusive value="2"/>
     </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="integer_minmaxInclusive_marker">
     <xs:restriction base="xs:integer">
       <xs:minInclusive value="10"/>
       <xs:maxInclusive value="1000000"/>
     </xs:restriction>
   </xs:simpleType>

   <!-- document element -->
   <xs:element name="parameters">
     <xs:complexType>
       <xs:all>
         <xs:element ref="shot_number" minOccurs="1"/>
         <xs:element ref="input_run" minOccurs="1"/>
         <xs:element ref="output_run" minOccurs="1"/>
         <xs:element ref="user_in" minOccurs="1"/>
         <xs:element ref="machine" minOccurs="1"/>
         <xs:element ref="time_to_simulate" minOccurs="1"/>
       </xs:all>
     </xs:complexType>
   </xs:element>
 
   <!-- Input shot number -->
   <xs:element name="shot_number" type="integer_minmaxInclusive_shot">
      <xs:annotation>
          <xs:documentation>Input shot number</xs:documentation>
      </xs:annotation>
   </xs:element>

   <!-- Input run number -->
   <xs:element name="input_run" type="integer_minmaxInclusive_run">
      <xs:annotation>
          <xs:documentation>Input run number</xs:documentation>
      </xs:annotation>
   </xs:element>
  
   <!-- Output run number -->
   <xs:element name="output_run" type="integer_minmaxInclusive_run">
      <xs:annotation>
          <xs:documentation>Output run number</xs:documentation>
      </xs:annotation>
   </xs:element>
  
    <!-- Username for input/output database -->
   <xs:element name="user_in" type="xs:string">
      <xs:annotation>
          <xs:documentation>Username for input/output database</xs:documentation>
      </xs:annotation>
   </xs:element>
  
   <!-- Machine name for input/output database -->
   <xs:element name="machine" type="xs:string">
      <xs:annotation>
          <xs:documentation>Machine name for input/output database</xs:documentation>
      </xs:annotation>
   </xs:element>
  
   <!-- Time to simulate (if <0: use IDS first time slice; if =0: use IDS whole time vector; if >0: use the specified time slice) -->
   <xs:element name="time_to_simulate" type="xs:float">
      <xs:annotation>
          <xs:documentation>Time to simulate (if negative: use IDS first time slice; if =0: use IDS whole time vector; if positive: use the specified time slice)</xs:documentation>
      </xs:annotation>
   </xs:element>
  
</xs:schema>
 
