#!/usr/bin/env python

# ---------------------------------------------------
# LIST LOCAL STATUS OF ACTORS OF THE HCD WORKFLOW(S)
# ---------------------------------------------------

import os

root_directory = '/home/ITER/schneim/public/git'
#root_directory = '/home/ITER/mitterv/codes'
#root_directory = '/home/ITER/weia/codes'

list_of_projects = ['hcd','hcd-wf','nemo','spot','risk','ids-tools','genray','gray','grayscale','fpsim/tools','hcd2core-sources','hcd2core-profiles','ascot','core_sources-combiner','stixredist','tomcat','cyrano','lion','pion']

print('--------------------------------------------------------------------------------------------')
print('ACTORS                    ACTIVE BRANCH                LOCAL COMMITS          LOCAL CHANGES')
print('---                       ---                          ---                    ---')
for project in list_of_projects:
   os.chdir(root_directory+'/'+project)
   mybranch = os.popen("git branch | awk '/\*/ { print $2; }'").read()
   firsttab    = ' '*(26 - len(project))
   line_to_print = project+firsttab+mybranch[:-1]
   if len(os.popen('git diff '+mybranch[:-1]+' origin/'+mybranch[:-1]).read())>0:
      secondtab = ' '*(29 - len(mybranch[:-1]))
      line_to_print = (line_to_print)+secondtab+'! local commits !'
   if len(os.popen('git status | grep "modified:"').read())>0:
      thirdtab = ' '*(78 - len(line_to_print))
      line_to_print = line_to_print+thirdtab+'! local changes !'
   print(line_to_print)

print('--------------------------------------------------------------------------------------------')





