#!/usr/bin/env python

# ---------------------------------------------------
# LIST LOCAL STATUS OF ACTORS OF THE HCD WORKFLOW(S)
# ---------------------------------------------------

import os

root_public    = '/home/ITER/schneim/public/git'
root_nolicense = '/home/ITER/schneim/public/git/nolicense'

public_projects = ['hcd','nemo','spot','risk','wftools','grayscale','hcd2core-sources','hcd2core-profiles']

nolicense_projects = ['genray','gray','fpsim/tools','ascot','stixredist','tomcat','cyrano','lion','pion']

print('--------------------------------------------------------------------------------------------')
print('ACTORS                    ACTIVE BRANCH                LOCAL COMMITS          LOCAL CHANGES')
print('---                       ---                          ---                    ---')
for project in public_projects:
   os.chdir(root_public+'/'+project)
   mybranch = os.popen("git branch | awk '/\*/ { print $2; }'").read()
   firsttab    = ' '*(26 - len(project))
   line_to_print = project+firsttab+mybranch[:-1]
   if len(os.popen('git diff '+mybranch[:-1]+' origin/'+mybranch[:-1]).read())>0:
      secondtab = ' '*(29 - len(mybranch[:-1]))
      line_to_print = (line_to_print)+secondtab+'! local commits !'
   if len(os.popen('git status | grep "modified:"').read())>0:
      thirdtab = ' '*(78 - len(line_to_print))
      line_to_print = line_to_print+thirdtab+'! local changes !'
   print(line_to_print)

for project in nolicense_projects:
   os.chdir(root_nolicense+'/'+project)
   mybranch = os.popen("git branch | awk '/\*/ { print $2; }'").read()
   firsttab    = ' '*(26 - len(project))
   line_to_print = project+firsttab+mybranch[:-1]
   if len(os.popen('git diff '+mybranch[:-1]+' origin/'+mybranch[:-1]).read())>0:
      secondtab = ' '*(29 - len(mybranch[:-1]))
      line_to_print = (line_to_print)+secondtab+'! local commits !'
   if len(os.popen('git status | grep "modified:"').read())>0:
      thirdtab = ' '*(78 - len(line_to_print))
      line_to_print = line_to_print+thirdtab+'! local changes !'
   print(line_to_print)

print('--------------------------------------------------------------------------------------------')





