#example
---
SOURCES:
  - VCS:  git
    REPO: ssh://git@git.iter.org/imas/training.git
    VERSION: develop
    DIR: training

MODULES: [IMAS, iWrap, XMLlib]

BUILDS: 
  - DIR: training/level2/fortran
    CMD: make

ACTORS: 
  - DIR: training/level2/fortran
    XML: physics_model_level2.yaml

#COMMENTS:  
...
